ExamensProjekt/GameOfDojan/Controllers/ShoePicController.cs
using GameOfDojan.Models;
using GameOfDojan.Services;
using GameOfDojan.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;

namespace GameOfDojan.Controllers
{
    public class ShoePicController : Controller
    {
        private readonly IShoePicService _shoePicService;
        private readonly IAiService _aiService;
        private readonly UserService _userService;
        private readonly IShoePicData _shoePicData;
        private readonly IUserData _userData;
        private readonly ICommentData _commentData;

        public ShoePicController(
            IShoePicService shoePicService,
            IAiService aiService,
            UserService userService,
            IShoePicData shoePicData,
            IUserData userData,
            ICommentData commentData
            )
        {
            _shoePicService = shoePicService;
            _aiService = aiService;
            _userService = userService;
            _shoePicData = shoePicData;
            _userData = userData;
            _commentData = commentData;
        }

        public IActionResult Index()
        {
            if (UserIsAuthenticated())
            {
                return View();
            }
            else
            {
                return RedirectToPage("/Account/LogIn", "", new { area = "Identity" });
            }
        }

        private bool UserIsAuthenticated()
        {
            if (HttpContext.User.Identity.IsAuthenticated)
                return true;
            else
                return false;
        }

        public IActionResult AllShoePics()
        {
            var shoePics = _shoePicData.GetAllShoePics();


            return View("AllShoePics", shoePics);
        }

        [HttpPost]
        public async Task<IActionResult> UploadPic(List<IFormFile> files)
        {
            var filePath = "";
            try
            {
                filePath = await _shoePicService.AddPicToFolder(files);
            }
            catch (Exception)
            {
                return BadRequest();
            }

            var PredictionAnswer = await _aiService.MakePredictionRequest(filePath);/*new Rootobject
            {
                Predictions = new Prediction[]{
                    new Prediction()
                    {
                        Probability = 0.8F,
                        TagName = "konsultdoja"
                    }
                }
            };*/

            var shoePic = await CreateShoePic(PredictionAnswer, filePath);
            UploadPicToDataBase(shoePic);
            return View("AiResponse", shoePic);
        }

        public IActionResult GiveShoePicALike(int id)
        {
         
            if (UserIsAuthenticated())
            {
                var currentUserId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
                try
                {
                    _shoePicData.GiveShoePicALike(id, currentUserId);
                }
                catch (Exception ex)
                {
                    return BadRequest(ex);
                }
                var shoePic = _shoePicData.GetShoePicWithComments(id);
                return View("ShoePicWithComments", shoePic);
            }
            else
            {
                return RedirectToPage("/Account/LogIn", "", new { area = "Identity" });
            }

        }

        private async Task<ShoePic> CreateShoePic(Rootobject predictionAnswer, string filePath)
        {
            var userId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var newUser = await _userService.GetUser(userId);

            var shoePic = new ShoePic
            {
                ImageSource = filePath.Substring(8),
                ApplicationUser = newUser,
                Uploaded = DateTime.Now
            };

            foreach (var item in predictionAnswer.Predictions)
            {
                if (item.TagName == "konsultdoja")
                    shoePic.Probability = item.Probability;
            }
            return shoePic;
        }

        private void UploadPicToDataBase(ShoePic shoePic)
        {
            if (shoePic.Probability > 0.7 && shoePic.Probability < 1)
            {
                _shoePicData.AddPictureToDatabase(shoePic);
                _userData.AddPointToUser(shoePic.ApplicationUser);
            }
        }

        public IActionResult ShoePicWithComments(int id)
        {
            var shoePic = _shoePicData.GetShoePicWithComments(id);
            return View("ShoePicWithComments", shoePic);
        }

        public IActionResult AddCommentToShoePic(string text, int shoePicId)
        {
            if (UserIsAuthenticated())
            {
                var currentUserId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
                //var currentUser = _userData.GetUser(currentUserId);
                _commentData.AddComment(text, shoePicId, currentUserId);
                var shoePic = _shoePicData.GetShoePicWithComments(shoePicId);

                return View("ShoePicWithComments", shoePic);
            }
            else
            {
                return RedirectToPage("/Account/LogIn", "", new { area = "Identity" });
            }
        }

        public IActionResult UpdateDescriptionToShoePic(string description, int shoePicId)
        {
            _shoePicData.UpdateShoePicDescription(description, shoePicId);
            var shoePic = _shoePicData.GetShoePicWithComments(shoePicId);
            return View("ShoePicWithComments", shoePic);
        }
    }
}

ExamensProjekt/GameOfDojan/Controllers/UserController.cs
using GameOfDojan.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace GameOfDojan.Controllers
{
    public class UserController : Controller
    {
        private readonly UserService _userService;
        private readonly IUserData _userData;

        public UserController(UserService userService, IUserData userData)
        {
            _userService = userService;
            _userData = userData;
        }

        public async Task<IActionResult> Index()
        {
            var userId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var newUser = await _userService.GetUser(userId);

            return View(newUser);
        }


    }
}

ExamensProjekt/GameOfDojan/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Game of Dojan</title>

    <link rel="shortcut icon" type="image/x-icon" href="~/Logo/Dojanlogo.PNG"/>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"><img id="navbar-logo" src="~/Logo/dojan.png"/></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="ShoePic" asp-action="Index">Ladda upp bild</a></li>
                    <li><a asp-area="" asp-controller="ShoePic" asp-action="AllShoePics">Alla bilder</a></li>

                    @*<li><a asp-area="" asp-controller="Statistics" asp-action="Index">Statistik</a></li>*@
                    @*<li><a asp-area="" asp-controller="User" asp-action="Index">Konto</a></li>*@

                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    @*<partial name="_CookieConsentPartial" />*@

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Game of Dojan</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>